version: '3.8'

networks:
  net_redis:
    driver: bridge

services:
  redis-commander:
    image: rediscommander/redis-commander:latest
    
    ports:
      - 80:8081
    
    networks:
      - net_redis
    
    depends_on:
      - db_redis
    
    environment:
      - REDIS_HOSTS=desafio-04_net_redis:desafio-04-db_redis-1:6379

  db_redis:
    image:  redis
    
    ports:
      - 6379:6379

    volumes:
      - /serverv/data:/data/redis-server

    networks:
      - net_redis
    
  
